config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  get 'search' => 'profiles#index', as: 'profiles_index'

  root 'home#index'

  devise_for :users

  resources :roles, only: [:index, :new, :create, :edit, :update]
  
  resources :levels, only: [:index, :new, :create, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update] do
    resources :requirements, only: [:destroy]
  end
  
  resources :profiles, only: [:show, :new, :create, :update]  do
    member do
      get 'edit_info'
      get 'edit_description'
      get 'edit_level'
    end
    resources :repositories, only: [:new, :create, :edit, :update, :destroy]
    resources :jobs, only: [:new, :create, :edit, :update, :destroy]
    resources :educations, only: [:new, :create, :edit, :update, :destroy]
    

    # ### verificar si se van a usar
    # resources :skills, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    #   collection do  
    #     get 'add'
    #     post 'added'
    #   end
    # end    
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :show]
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :place, :qualification, :discipline, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/fullfillment.rb
class Fullfillment < ApplicationRecord
  belongs_to :profile
  belongs_to :requirement
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :company, :position, :description, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :profiles, dependent: :destroy

   #### Validaciones
   validates :name, :positive_description, :negative_description, presence: {message: '*No puede dejarse vacio'}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :repositories, dependent: :destroy
  belongs_to :level
  has_many :jobs, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_and_belongs_to_many :skills, dependent: :destroy
  has_many :fullfillments
  has_many :requirements, through: :fullfillments, dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :user, update_only: true

  #### Validaciones
  validates :country, :about, :level_id, presence: {message: '*No puede dejarse vacio'}
  

  def self.search(search)
    wildcard_search = user_name = user_lastname = "%#{search}%"
    if search.split.length > 1
      user_name = "%#{search.split[0]}%"
      user_lastname = "%#{search.split[1]}%"
    end

    User.where("name LIKE ? OR lastname LIKE ? OR email LIKE ?", user_name, user_lastname, wildcard_search)
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :link, presence: {message: '*No puede dejarse vacio'}
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :skill
  has_many :fullfillments
  has_many :profiles, through: :fullfillments, dependent: :destroy

  #### Validaciones
  # validates :name, presence: {'*No puede dejarse vacio'}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy

  #### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :profiles, dependent: :destroy
  has_many :requirements, dependent: :destroy

  accepts_nested_attributes_for :requirements, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  ##### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :profile

  #### Validaciones
  validates :name, :lastname, presence: {message: '*No puede dejarse vacio'}
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/admin/index.html.haml
.col
  .row.justify-content-center
    #Admin-Panel.col-10.card.p-4.text-center.profile-border-shadow
      %h3.pb-4 Panel Administrativo
      .row.border.border-light
        #Roles.col.profile-border-shadow.rounded.mr-3.border.border-light.pb-2.pt-2
          = fa_icon "user", class: "fa-7em text-primary pb-2"
          %h2
            = @roles.length
          = link_to 'Roles', roles_path, class: 'text-white btn btn-success col'
        #Levels.col.profile-border-shadow.rounded.mr-3.border.border-light.pb-2.pt-2
          = fa_icon "signal", class: "fa-7em text-primary pb-2"
          %h2
            = @levels.length
          = link_to 'Niveles', levels_path, class: 'text-white btn btn-success col'
        #Skills.col.profile-border-shadow.rounded.border.border-light.pb-2.pt-2
          = fa_icon "puzzle-piece", class: "fa-7em text-primary pb-2"
          %h2
            = @skills.length
          = link_to 'Habilidades', skills_path, class: 'text-white btn btn-success col'

app/views/partials/_footer.html.haml
.col-sm-12.px-0
 
  %nav.navbar.navbar-light.p-0
    .col.d-flex.justify-content-center
      %h5.m-0  Encuentra compañeros de trabajo
    .col

      -#  NT: ↓↓ (user_session_path) lo use solo para ver la vista igual para (method: :get) cambielos segun les convenga ↓↓

      = form_tag user_session_path, class: '',  method: :get do 
        .row
          .col-4

            = text_field_tag "", "", placeholder: "Nombre", class: 'form-control'
          .col-4

            = text_field_tag "", "", placeholder: 'Apellido', class: 'form-control'
          .col-4

            = button_tag(type: "submit", class: "btn btn-success btn-block") do
    
              %p.m-0 buscar


-#            
-#  = form_tag _search_path, class: 'form-inline', method: :get do
-#      = text_field_tag :keywords, params[:keywords], class: 'flex-2 form-control mr-2', placeholder: 'Busqueda de empleados'

app/views/partials/_navbar.html.haml
- if user_signed_in?
  #Nav.col
    .row.align-items-center
      .col-2.text-center
        = link_to root_path do
          = image_tag 'logo.png', class: 'user-nbar-logo'

      -# ----- Buscador -----        
      
      .col-6.text-left
        = render template: 'profiles/search'
      .col-4
        .row
          .col-2
          .col-8
            -if current_user.role.name === 'ADMINISTRADOR' 
              %div
                %button.btn.btn-primary.position-absolute.rounded-circle
                  %h6.text-white.m-0
                    = "#{current_user.name.first.upcase}"
                .bg-light.ml-4.p-1.pl-3
                  %span.badge.text-dark.dropdown-toggle{"data-toggle" => "dropdown"}
                    = "#{current_user.name.titleize} #{current_user.lastname.titleize}"
                  .dropdown-menu
                    = link_to 'Panel Administrativo', admin_path, class: 'dropdown-item'
                    = link_to 'Cerrar sesion', destroy_user_session_path, method: :delete, class: 'dropdown-item'
            - elsif current_user.role.name === 'USUARIO' && current_user.profile != nil && current_user.profile.persisted?
              %div
                %button.btn.btn-primary.position-absolute.rounded-circle
                  %h6.text-white.m-0
                    = "#{current_user.name.first.upcase}"
                .bg-light.ml-4.p-1.pl-3                           
                  %span.badge.text-dark.dropdown-toggle{"data-toggle" => "dropdown"}
                    = "#{current_user.name.titleize} #{current_user.lastname.titleize}"
                  .dropdown-menu
                    = link_to 'Ver mi perfil', profile_path(current_user.profile), class: 'dropdown-item'
                    = link_to 'Cerrar sesion', destroy_user_session_path, method: :delete, class: 'dropdown-item'
          .col-1        
- else
  = render template: 'devise/sessions/login_form'