config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  get 'search' => 'profiles#index', as: 'profiles_index'

  root 'home#index'

  devise_for :users

  resources :roles, only: [:index, :new, :create, :edit, :update]
  
  resources :levels, only: [:index, :new, :create, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update] do
    resources :requirements, only: [:destroy]
  end
  
  resources :profiles, only: [:show, :new, :create, :update]  do
    member do
      get 'edit_info'
      get 'edit_description'
      get 'edit_level'
    end
    resources :repositories, only: [:new, :create, :edit, :update, :destroy]
    resources :jobs, only: [:new, :create, :edit, :update, :destroy]
    resources :educations, only: [:new, :create, :edit, :update, :destroy]
    

    # ### verificar si se van a usar
    # resources :skills, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    #   collection do  
    #     get 'add'
    #     post 'added'
    #   end
    # end    
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :show]
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :place, :qualification, :discipline, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/fullfillment.rb
class Fullfillment < ApplicationRecord
  belongs_to :profile
  belongs_to :requirement
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :company, :position, :description, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :profiles, dependent: :destroy

   #### Validaciones
   validates :name, :positive_description, :negative_description, presence: {message: '*No puede dejarse vacio'}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :repositories, dependent: :destroy
  belongs_to :level
  has_many :jobs, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_and_belongs_to_many :skills, dependent: :destroy
  has_many :fullfillments
  has_many :requirements, through: :fullfillments, dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :user, update_only: true

  #### Validaciones
  validates :country, :about, :level_id, presence: {message: '*No puede dejarse vacio'}
  

  def self.search(search)
    wildcard_search = user_name = user_lastname = "%#{search}%"
    if search.split.length > 1
      user_name = "%#{search.split[0]}%"
      user_lastname = "%#{search.split[1]}%"
    end

    User.where("name LIKE ? OR lastname LIKE ? OR email LIKE ?", user_name, user_lastname, wildcard_search)
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :link, presence: {message: '*No puede dejarse vacio'}
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :skill
  has_many :fullfillments
  has_many :profiles, through: :fullfillments, dependent: :destroy

  #### Validaciones
  # validates :name, presence: {'*No puede dejarse vacio'}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy

  #### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :profiles, dependent: :destroy
  has_many :requirements, dependent: :destroy

  accepts_nested_attributes_for :requirements, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  ##### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :profile

  #### Validaciones
  validates :name, :lastname, presence: {message: '*No puede dejarse vacio'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :create]
  before_action :set_job, only: [:edit, :update, :destroy]

  def index
    @jobs = Job.find_or_initialize_by(id: params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = @profile.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to  profile_path(@profile) }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to profile_path(@job.profile) }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(@job.profile) }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def job_params
      params.require(:job).permit(:company, :position, :description, :start_date, :finish_date, :profile_id)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
   before_action :authenticate_user!
   before_action :set_skill, only: [:edit, :update]
 
   def index
    @skills = Skill.all
   end
 
   def new
     @skill = Skill.new
   end
 
   def create
     @skill = Skill.new(skill_params)
 
     respond_to do |format|
       if @skill.save
         format.html { redirect_to skills_path }
         format.json { render :show, status: :created, location: @skill }
       else
         format.html { render :new }
         format.json { render json: @skill.errors, status: :unprocessable_entity }
       end
     end
   end
 
   def edit
 
   end
 
   def update
     respond_to do |format|
       if @skill.update(skill_params)
        #  format.html { redirect_to skills_path }
         format.html { redirect_to edit_skill_url(@skill)}
         format.json { render :show, status: :ok, location: @skill }
       else
         format.html { render :edit }
         format.json { render json: @skill.errors, status: :unprocessable_entity }
       end
     end
   end

  #  ##### TODAVIA FALTA
  #  def add
  #   # # @profile = Profile.find(id: params[:profile_id])
  #   @skills = Skill.all
  #   # @skills.requirements

  #   # @requirement = 
  #  end

  #   ##### TODAVIA FALTA
  #  def added
  #   # @profile.skills << @skill

  #   # @requirement.fullfillment << requirement_ids
    
  #  end
 
   private
     
     def set_skill
       @skill = Skill.find(params[:id])
     end
 
     def skill_params
       params.require(:skill).permit(:name, :profile_id, requirements_attributes:[:name])
     end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_edit_form.html.haml
= form_for @skill do |f|
  .form-group
    = f.label 'Nombre'
    = f.text_field :name, class: 'form-control'
    - if @skill.errors[:name].any?
      .text-danger 
        = @skill.errors[:name].to_s[/\w([^"]*)/]
  %hr.line-border-shadow.my-4/
  %h4.text-center Nuevo Requerimiento
  = f.fields_for :requirements, Requirement.new do |r|
    .form-group
      = r.label 'Nombre'
      = r.text_field :name, class: 'form-control'
  %hr.line-border-shadow.my-4/
  %h5.text-center= "Requerimientos de #{@skill.name}" 
  .row
    - @skill.requirements.each do |c|
      .col-4
        %small= "| #{c.name} |"
        = link_to skill_requirement_path(@skill, c), method: :delete do
          = fa_icon "trash", class: "fa-xs text-danger"
  .actions
    .row.mt-4
      .col-3
        = f.submit 'Guardar', class: 'btn btn-success text-white'
      .col-3
        = link_to 'Regresar', skills_path, class: "btn cancel-button buttons-border"

app/views/skills/_form.html.haml
= form_for @skill do |f|
  .form-group
    = f.label 'Nombre'
    = f.text_field :name, class: 'form-control'
    - if @skill.errors[:name].any?
      .text-danger 
        = @skill.errors[:name].to_s[/\w([^"]*)/]
  .actions
    .row.mt-4
      .col-3
        = f.submit 'Guardar', class: 'btn btn-success text-white'
      .col-3
        = link_to 'Regresar', skills_path, class: "btn cancel-button buttons-border"

app/views/skills/add.html.haml
-##### todavia falta
.col
  .row.justify-content-center
    #Add-Skill.col-6
      .card.p-4
        %h3.text-center.mb-4 Agregar Habilidad
        = form_for :skill, url: added_profile_skills_path do |f|
          .form-group
            = f.label :skill, 'Seleccione'
            = f.collection_select :skill, Skill.all, :id, :name

          - @skills.each do |skill| 
            .field
              = f.collection_check_boxes :skill, Skill.find(skill.id).requirements, :id, :name
             
          .actions
            = f.submit 'Guardar', class: 'btn btn-success btn-block text-white

app/views/skills/edit.html.haml
.col
  .row.justify-content-center
    #Edit-Skill.col-4
      .card.p-4.profile-border-shadow
        %h3.text-center.mb-4 Editar Habilidad
        = render 'edit_form', skill: @skill

app/views/skills/index.html.haml
- if user_signed_in?
  - if current_user.role.name === 'ADMINISTRADOR'
    #List-Skills.col
      .row.justify-content-center
        .col-8.card.p-5.profile-border-shadow.mb-4
          .row
            .col
              %h3.text-center Habilidades Cargadas
            .col-2.text-center
              = link_to new_skill_path do
                = fa_icon "plus-circle", class: "fa-2x text-success"
            - if @skills.empty?
              %h4 No Existen Habilidades Cargadas
            - else
              %table.table.mt-2
                %thead
                  %tr
                    %th Nombre
                    %th Requerimientos
                    %th Acciones
                %tbody
                  - @skills.each do |skill|
                    %tr
                      %td
                        = skill.name
                      %td
                        - skill.requirements.each_with_index do |requirement, index|
                          = "#{index + 1}-) #{requirement.name}, "
                      %td
                        = link_to edit_skill_path(skill) do
                          = fa_icon "pencil", class: "fa-lg text-secondary mr-2"
                        = link_to "" do
                          = fa_icon "trash", class: "fa-lg text-danger"   #### #### agregar ruta de elimnar
          .row
            .col.text-center
              = link_to 'Regresar', admin_path, class: "btn cancel-button buttons-border"
  - else
    .col
      .row
        #List-Skills.col-10
          %p.title-font
            Habilidades
        .col-2.text-center
          - if user_signed_in?
            - if @profile.user_id === current_user.id
              = link_to profile_path(current_user.profile) do
                = fa_icon "plus-circle", class: "fa-2x text-success"
      - if @profile.skills.empty?
        .col
      - else
        .row.ml-5.mt-4.mr-5
          - @profile.skills.each do |skill|
            #Skill.col-10
              .row.pb-2
                .col-3.pl-0
                  .bg-secondary.rounded-skill.text-center
                    %strong
                      %span.text-white
                        = skill.name
              .row 
                .col
                  .row.text-center
                    - skill.requirements.each do |requirement|
                      - requirement.fullfillments.each do |fullfillment|
                        - if fullfillment.status == true
                          .col.border.border-secondary.bg-info
                            %span.text-white
                              = requirement.name
                        - else
                          .col.border.border-secondary.bg-danger
                            %span.text-white
                              = requirement.name
              %hr.line-border-shadow/
            .col-2
              .row
                - if user_signed_in?
                  - if @profile.user_id === current_user.id
                    .col-6.text-right
                      = link_to "" do
                        = fa_icon "pencil", class: "fa-lg text-secondary"   #### agregar ruta de editar
                    .col-6.text-right
                      = link_to "" do
                        = fa_icon "trash", class: "fa-lg text-danger"   #### #### agregar ruta de elimnar
- else
  .col
    .row
      #List-Skills.col
        %p.title-font Habilidades      
    - if @profile.skills.empty?
      .col
    - else
      .row.ml-5.mt-4.mr-5
        - @profile.skills.each do |skill|
          #Skill.col-10
            .row.pb-2
              .col-3.pl-0
                .bg-secondary.rounded-skill.text-center
                  %strong
                    %span.text-white
                      = skill.name
            .row 
              .col
                .row.text-center
                  - skill.requirements.each do |requirement|
                    - requirement.fullfillments.each do |fullfillment|
                      - if fullfillment.status == true
                        .col.border.border-secondary.bg-info
                          %span.text-white
                            = requirement.name
                      - else
                        .col.border.border-secondary.bg-danger
                          %span.text-white
                            = requirement.name
            %hr.line-border-shadow/
                      

app/views/skills/new.html.haml
.col
  .row.justify-content-center
    #NeW-Skill.col-4
      .card.p-4.profile-border-shadow
        %h3.text-center.mb-4 Nueva Habilidad
        = render 'form'
        