config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  get 'search' => 'profiles#index', as: 'profiles_index'

  root 'home#index'

  devise_for :users

  resources :roles, only: [:index, :new, :create, :edit, :update]
  
  resources :levels, only: [:index, :new, :create, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update] do
    resources :requirements, only: [:destroy]
  end
  
  resources :profiles, only: [:show, :new, :create, :update]  do
    member do
      get 'edit_info'
      get 'edit_description'
      get 'edit_level'
    end
    resources :repositories, only: [:new, :create, :edit, :update, :destroy]
    resources :jobs, only: [:new, :create, :edit, :update, :destroy]
    resources :educations, only: [:new, :create, :edit, :update, :destroy]
    

    # ### verificar si se van a usar
    # resources :skills, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    #   collection do  
    #     get 'add'
    #     post 'added'
    #   end
    # end    
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :show]
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :place, :qualification, :discipline, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/fullfillment.rb
class Fullfillment < ApplicationRecord
  belongs_to :profile
  belongs_to :requirement
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :company, :position, :description, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :profiles, dependent: :destroy

   #### Validaciones
   validates :name, :positive_description, :negative_description, presence: {message: '*No puede dejarse vacio'}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :repositories, dependent: :destroy
  belongs_to :level
  has_many :jobs, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_and_belongs_to_many :skills, dependent: :destroy
  has_many :fullfillments
  has_many :requirements, through: :fullfillments, dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :user, update_only: true

  #### Validaciones
  validates :country, :about, :level_id, presence: {message: '*No puede dejarse vacio'}
  

  def self.search(search)
    wildcard_search = user_name = user_lastname = "%#{search}%"
    if search.split.length > 1
      user_name = "%#{search.split[0]}%"
      user_lastname = "%#{search.split[1]}%"
    end

    User.where("name LIKE ? OR lastname LIKE ? OR email LIKE ?", user_name, user_lastname, wildcard_search)
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :link, presence: {message: '*No puede dejarse vacio'}
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :skill
  has_many :fullfillments
  has_many :profiles, through: :fullfillments, dependent: :destroy

  #### Validaciones
  # validates :name, presence: {'*No puede dejarse vacio'}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy

  #### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :profiles, dependent: :destroy
  has_many :requirements, dependent: :destroy

  accepts_nested_attributes_for :requirements, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  ##### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :profile

  #### Validaciones
  validates :name, :lastname, presence: {message: '*No puede dejarse vacio'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :create]
  before_action :set_job, only: [:edit, :update, :destroy]

  def index
    @jobs = Job.find_or_initialize_by(id: params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = @profile.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to  profile_path(@profile) }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to profile_path(@job.profile) }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(@job.profile) }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def job_params
      params.require(:job).permit(:company, :position, :description, :start_date, :finish_date, :profile_id)
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_level, only: [:edit, :update]


  def index
   @levels = Level.all
  end
  
  def show
    
  end

  def new
    @level = Level.new
  end

  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to  levels_path }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to levels_path }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_level
      @level = Level.find(params[:id])
    end

    def level_params
      params.require(:level).permit(:name, :positive_description, :negative_description)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/levels/_form.html.haml
= form_for @level do |f|
  .form-group
    = f.label 'Nombre', class: "text-3rd-font bold"
    = f.text_field :name, class: 'form-control'
    - if @level.errors[:name].any?
      .text-danger 
        = @level.errors[:name].to_s[/\w([^"]*)/]
  .form-group
    = f.label 'Descripción Positiva', class: "text-3rd-font bold"
    = f.trix_editor :positive_description, class: 'form-control'
    - if @level.errors[:positive_description].any?
      .text-danger 
        = @level.errors[:positive_description].to_s[/\w([^"]*)/]
  .form-group
    = f.label 'Descripción Negativa', class: "text-3rd-font bold"
    = f.trix_editor :negative_description, class: 'form-control'
    - if @level.errors[:negative_description].any?
      .text-danger 
        = @level.errors[:negative_description].to_s[/\w([^"]*)/]
  .actions
    .row.mt-4
      .col-3
        = f.submit 'Guardar', class: 'btn btn-success buttons-border'
      .col-3
        = link_to 'Regresar', levels_path, class: "btn cancel-button buttons-border"

app/views/levels/edit.html.haml
.col
  .row.justify-content-center
    #Edit-Level.col-6
      .card.p-4.profile-border-shadow.mb-4
        %p.text-1st-font.bold.text-center.mb-4 Editar Nivel
        = render 'form', role: @level

app/views/levels/index.html.haml
- if user_signed_in?
  - if current_user.role.name === 'ADMINISTRADOR'
    #List-Levels.col
      .row.justify-content-center
        .col-8.card.p-5.profile-border-shadow.mb-4
          .row
            .col
              %p.text-1st-font.bold.text-center Niveles Cargados
            .col-2.text.center
              = link_to new_level_path do
                = fa_icon "plus-circle", class: "fa-2x text-success"
            - if @levels.empty?
              %h4 No Existen Niveles Cargados
            - else
              %table.table
                %thead
                  %tr
                    %th.text-3rd-font Nombre
                    %th.text-3rd-font Descripión Positiva
                    %th.text-3rd-font Descripión Negativa
                    %th.text-3rd-font Acciones
                %tbody
                  - @levels.each do |level|
                    %tr
                      %td.text-4th-font
                        = level.name
                      %td.text-4th-font
                        = sanitize(level.positive_description).html_safe
                      %td.text-4th-font
                        = sanitize(level.negative_description).html_safe
                      %td
                        = link_to edit_level_path(level) do
                          = fa_icon "pencil", class: "fa-lg text-secondary mr-2"
                        = link_to "" do
                          = fa_icon "trash", class: "fa-lg text-danger"   #### #### agregar ruta de elimnar
          .row
            .col.text-center
              = link_to 'Regresar', admin_path, class: "btn cancel-button buttons-border"

app/views/levels/new.html.haml
.col
  .row.justify-content-center
    #NeW-Level.col-6
      .card.p-4.profile-border-shadow.mb-4
        %p.text-1st-font.bold.text-center.mb-4 Nuevo Nivel
        = render 'form'

app/views/levels/show.html.haml
.col
  .row
    #List-Skills.col-10
      %p.title-font 
        Nivel
    .col-2.text-center
      - if user_signed_in?
        - if @profile.user_id === current_user.id
          = link_to edit_level_profile_path(@profile) do
            = fa_icon "pencil", class: "fa-2x text-secondary"
      -### pinta el nivel seleccionado mas los anteriores
  .row
    .col-12
      .row
        .col.ml-5.mt-4.mr-5
          .row.justify-content-center
            - @levels.each do |level|
              - if level.id < @profile.level_id
                .col-5.card.mb-3.ml-2.profile-border-shadow
                  %p.text-center.text-1st-font
                    = level.name
                  %hr.line-border-shadow.mt-0/
                  %p.text-2nd-font Descripcion Positiva:
                  .row.my-2
                    .col-12.text-4th-font
                      = sanitize(level.positive_description).html_safe
            .col-5.card.mb-3.ml-2.profile-border-shadow
              %p.text-center.text-1st-font
                = @profile.level.name
              %hr.line-border-shadow.mt-0/
              %p.text-2nd-font Descripcion Positiva: 
              .row.my-2
                .col-12.text-4th-font
                  = sanitize(@profile.level.positive_description).html_safe
              %hr.line-border-shadow/
              %p.text-2nd-font Descripcion Negativa:
              .row.my-2
                .col-12.text-4th-font
                  = sanitize(@profile.level.negative_description).html_safe