config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  get 'search' => 'profiles#index', as: 'profiles_index'

  root 'home#index'

  devise_for :users

  resources :roles, only: [:index, :new, :create, :edit, :update]
  
  resources :levels, only: [:index, :new, :create, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update] do
    resources :requirements, only: [:destroy]
  end
  
  resources :profiles, only: [:show, :new, :create, :update]  do
    member do
      get 'edit_info'
      get 'edit_description'
      get 'edit_level'
    end
    resources :repositories, only: [:new, :create, :edit, :update, :destroy]
    resources :jobs, only: [:new, :create, :edit, :update, :destroy]
    resources :educations, only: [:new, :create, :edit, :update, :destroy]
    

    # ### verificar si se van a usar
    # resources :skills, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    #   collection do  
    #     get 'add'
    #     post 'added'
    #   end
    # end    
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :show]
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :place, :qualification, :discipline, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/fullfillment.rb
class Fullfillment < ApplicationRecord
  belongs_to :profile
  belongs_to :requirement
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :company, :position, :description, :start_date, :finish_date, presence: {message: '*No puede dejarse vacio'}
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :profiles, dependent: :destroy

   #### Validaciones
   validates :name, :positive_description, :negative_description, presence: {message: '*No puede dejarse vacio'}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :repositories, dependent: :destroy
  belongs_to :level
  has_many :jobs, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_and_belongs_to_many :skills, dependent: :destroy
  has_many :fullfillments
  has_many :requirements, through: :fullfillments, dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :user, update_only: true

  #### Validaciones
  validates :country, :about, :level_id, presence: {message: '*No puede dejarse vacio'}
  

  def self.search(search)
    wildcard_search = user_name = user_lastname = "%#{search}%"
    if search.split.length > 1
      user_name = "%#{search.split[0]}%"
      user_lastname = "%#{search.split[1]}%"
    end

    User.where("name LIKE ? OR lastname LIKE ? OR email LIKE ?", user_name, user_lastname, wildcard_search)
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :profile

  #### Validaciones
  validates :link, presence: {message: '*No puede dejarse vacio'}
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :skill
  has_many :fullfillments
  has_many :profiles, through: :fullfillments, dependent: :destroy

  #### Validaciones
  # validates :name, presence: {'*No puede dejarse vacio'}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy

  #### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :profiles, dependent: :destroy
  has_many :requirements, dependent: :destroy

  accepts_nested_attributes_for :requirements, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  ##### Validaciones
  validates :name, presence: {message: '*No puede dejarse vacio'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :profile

  #### Validaciones
  validates :name, :lastname, presence: {message: '*No puede dejarse vacio'}
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :create]
  before_action :set_education, only: [:edit, :update, :destroy]

  def index
    @eductions = Education.find_or_initialize_by(id: params[:id])
  end

  def new
    @education = Education.new
  end

  def create
    @education = @profile.educations.build(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to  profile_path(@profile) }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to profile_path(@education.profile) }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(@education.profile) }
      format.json { head :no_content }
    end
  end

  private

    def set_education
      @education = Education.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def education_params
      params.require(:education).permit(:place, :qualification, :discipline, :start_date, :finish_date, :profile_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :create]
  before_action :set_job, only: [:edit, :update, :destroy]

  def index
    @jobs = Job.find_or_initialize_by(id: params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = @profile.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to  profile_path(@profile) }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to profile_path(@job.profile) }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(@job.profile) }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def job_params
      params.require(:job).permit(:company, :position, :description, :start_date, :finish_date, :profile_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/educations/_form.html.haml
= form_for [:profile, @education] do |f|  
  .form-group.was-validated
    = f.label 'Universidad', class: "text-3rd-font bold"
    = f.text_field :place, class: 'form-control', required: true, placeholder: 'Introduce la universidad donde estudiaste'
    .invalid-feedback
      Falta completar este campo
    .valid-feedback
      Listo
  .form-group.was-validated
    = f.label 'Titulo', class: "text-3rd-font bold"
    = f.text_field :qualification, class: 'form-control', required: true, placeholder: 'Introduce el titulo obtenido'
    .invalid-feedback
      Falta completar este campo
    .valid-feedback
      Listo
  .form-group.was-validated
    = f.label 'Disciplina', class: "text-3rd-font bold"
    = f.text_field :discipline, class: 'form-control', required: true, placeholder: 'Introduce disciplina o carrera'
    .invalid-feedback
      Falta completar este campo
    .valid-feedback
      Listo
  .form-group.was-validated
    = f.label 'Desde el Año', class: "text-3rd-font bold"
    = f.date_field :start_date, class: 'form-control', required: true
    .invalid-feedback
      Falta completar este campo
    .valid-feedback
      Listo
  .form-group.was-validated
    = f.label 'Hasta el Año', class: "text-3rd-font bold"
    = f.date_field :finish_date, class: 'form-control', required: true
    .invalid-feedback
      Falta completar este campo
    .valid-feedback
      Listo
  .actions
    .row.mt-4
      .col-3
        = f.submit 'Guardar', class: 'btn btn-success buttons-border'
      .col-3
        = link_to 'Cancelar', profile_path(params[:profile_id]), class: "btn cancel-button buttons-border"

app/views/educations/edit.html.haml
.col-12
  .row.justify-content-center
    #Edit-Education.col-4
      .card.p-4.profile-border-shadow.mb-4
        %p.text-1st-font.bold.text-center.mb-4 Editar
        = render 'form', role: @education

app/views/educations/index.html.haml
.col
  .row
    #List-Educations.col-10
      %p.title-font
        Formación
    .col-2.text-center
      - if user_signed_in?
        - if @profile.user_id === current_user.id
          = link_to new_profile_education_path(@profile) do
            = fa_icon "plus-circle", class: "fa-2x text-success" 
  - if @profile.educations.empty?
    .col
  - else
    .row.ml-5.mt-4.mr-5 
      - @profile.educations.each do |education|
        #Education.col-10
          .row
            .col
              %p.text-1st-font
                = education.place
          .row
            .col
              %p.text-2nd-font
                = education.qualification
          .row
            .col
              %p.text-2nd-font
                = education.discipline
          .row
            .col
              %p.text-3rd-font
                = "#{education.start_date} al #{education.finish_date}"
              %hr.line-border-shadow/
        .col-2
          .row
            - if user_signed_in?
              - if @profile.user_id === current_user.id
                .col-6.text-right
                  = link_to edit_profile_education_path(@profile, education) do
                    = fa_icon "pencil", class: "fa-lg text-secondary"
                .col-6.text-right
                  = link_to  profile_education_path(@profile, education), method: :delete do
                    = fa_icon "trash", class: "fa-lg text-danger"

app/views/educations/new.html.haml
.col-12
  .row.justify-content-center
    #NeW-Education.col-4
      .card.p-4.profile-border-shadow.mb-4
        %p.text-1st-font.bold.text-center.mb-4 Nuevo
        = render 'form'